name: recomendations
version: '3.9'

services:
  mongo_db_recomendations:
    image: mongo:4.4.20-rc0-focal
    restart: always
    expose:
      - "27017"
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo_express_open_data:
    image: mongo-express:1.0.0-alpha
    restart: always
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db_recomendations
      ME_CONFIG_MONGODB_PORT: 27017

  fastapi-recomendations:
    container_name: $RECOMENDATIONS_HOST
    build:
      context: ./recomendations/src
    image: $RECOMENDATIONS_HOST
    env_file:
      - .env
    expose:
      - $RECOMENDATIONS_PORT
    volumes:
      - fastapi_recomendations_log:/usr/src/fastapi/logs
    restart: always
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b :$RECOMENDATIONS_PORT main:app

  nginx-recomendations:
    container_name: nginx-recomendations
    image: nginx:1.25-bookworm
    ports:
      - 80:80
    volumes:
      - nginx_recomendations_log:/var/log/nginx
      - ./ugc_service/ugc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ugc_service/ugc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - fastapi-recomendations
    restart: always

volumes:
  nginx_recomendations_log-ugc_log:
  fastapi_recomendations_log:
