name: ugc
version: '3.9'

services:
  mongo_db:
    image: mongo:4.4.20-rc0-focal
    restart: always
    expose:
      - "27017"
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "27017:27017"

  mongo_express_open_data:
    image: mongo-express:1.0.0-alpha
    restart: always
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"

  fastapi-main-ugc:
    container_name: $MAIN_UGC_HOST
    build:
      context: ./ugc_service/src
    image: $MAIN_UGC_HOST
    env_file:
      - .env
    expose:
      - $MAIN_UGC_PORT
    volumes:
      - fastapi_main_ugc_log:/usr/src/fastapi/logs
    restart: always
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b :$MAIN_UGC_PORT main:app

  nginx-main-ugc:
    container_name: nginx-main-ug
    image: nginx:1.25-bookworm
    ports:
      - 60:80
    volumes:
      - nginx_main-ugc_log:/var/log/nginx
      - ./ugc_service/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ugc_service/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - fastapi-main-ugc
    restart: always

volumes:
  nginx_main-ugc_log:
  fastapi_main_ugc_log:
