name: tests-movies
version: '3.9'

services:
  elastic-movies-test:
    env_file:
      - .env
    image: elasticsearch:8.12.2
    container_name: $MOVIES_TEST_ES_HOST
    expose:
      - $MOVIES_ES_PORT
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - ingest.geoip.downloader.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=true
      - logger.level=WARN
    healthcheck:
      test: curl -s -f http://localhost:9200 || exit 1
      interval: "10s"
      timeout: "1s"
      retries: 10
    mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: "no"

  redis-movies-test:
    env_file:
      - .env
    container_name: $MOVIES_TEST_REDIS_HOST
    image: redis:7.2.3-alpine3.19
    expose:
      - $MOVIES_REDIS_PORT
    restart: "no"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "10s"
      timeout: "1s"
      retries: 10
    command: redis-server --save 60 1 --loglevel notice

  fastapi-movies-test:
    env_file:
      - .env
    environment:
      - MOVIES_REDIS_HOST=$MOVIES_TEST_REDIS_HOST
      - MOVIES_ES_HOST=$MOVIES_TEST_ES_HOST
    container_name: $MOVIES_TEST_FASTAPI_HOST
    build:
      context: ./movies/fastapi_movies
    image: fastapi-movies
    volumes:
      - fastapi_movies_test_log:/usr/src/fastapi/logs
    expose:
      - $MOVIES_FASTAPI_PORT
    depends_on:
      elastic-movies-test:
        condition: service_healthy
      redis-movies-test:
        condition: service_healthy
    restart: "no"
    healthcheck:
      test: curl -s -f http://localhost:$MOVIES_FASTAPI_PORT/api/openapi || exit 1
      interval: "10s"
      timeout: "1s"
      retries: 10
    command: uvicorn main:app --host 0.0.0.0 --port $MOVIES_FASTAPI_PORT

  tests:
    env_file:
      - .env
    container_name: tests-movies
    build:
      context: ./movies/tests_movies
    image: tests_movies_img
    depends_on:
      fastapi-movies-test:
        condition: service_healthy
    command: poetry run pytest

volumes:
  fastapi_movies_test_log:
