name: ugc_recommendations
version: '3.9'

services:
  mongo_db:
    image: mongo:4.4.20-rc0-focal
    restart: always
    expose:
      - "27017"
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5

  fastapi-main-ugc:
    container_name: $MAIN_UGC_HOST
    build:
      context: ./ugc_service/src
    image: $MAIN_UGC_HOST
    env_file:
      - .env
    expose:
      - $MAIN_UGC_PORT
    volumes:
      - fastapi_main_ugc_log:/usr/src/fastapi/logs
    restart: always
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b :$MAIN_UGC_PORT main:app
    ports:
      - $MAIN_UGC_PORT:$MAIN_UGC_PORT

  nginx-main-ugc:
    container_name: nginx-main-ug
    image: nginx:1.25-bookworm
    ports:
      - 60:80
    volumes:
      - nginx_main-ugc_log:/var/log/nginx
      - ./ugc_service/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ugc_service/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - fastapi-main-ugc
    restart: always

  mongo_db_recommendations:
    image: mongo:4.4.20-rc0-focal
    restart: always
    expose:
      - "27017"
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5

  fastapi-recommendations:
    container_name: $RECOMMENDATIONS_HOST
    build:
      context: ./recomendations/src
    image: $RECOMMENDATIONS_HOST
    env_file:
      - .env
    expose:
      - $RECOMMENDATIONS_PORT
    volumes:
      - fastapi_recommendations_log:/usr/src/fastapi/logs
    restart: always
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b :$RECOMMENDATIONS_PORT main:app

  nginx-recommendations:
    container_name: nginx-recommendations
    image: nginx:1.25-bookworm
    ports:
      - 90:80
    volumes:
      - nginx_recommendations_log:/var/log/nginx
      - ./recomendations/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./recomendations/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - fastapi-recommendations
    restart: always

volumes:
  nginx_main-ugc_log:
  fastapi_main_ugc_log:
  nginx_recommendations_log:
  fastapi_recommendations_log:
