version: "3"

services:

  postgres:
    volumes:
      - ./postgres_to_elastic_etl/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"

  elasticsearch:
    ports:
      - "9200:9200"

  redis:
    ports:
      - "6379:6379"

  api:
    ports:
      - "8000:8000"
