"""Password can be NULL

Revision ID: 8cc452dca02b
Revises: 2ff62f45a743
Create Date: 2024-02-07 23:36:08.167623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cc452dca02b'
down_revision: Union[str, None] = '2ff62f45a743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'oauth_providers', ['id'])
    op.drop_column('oauth_providers', 'provider_data')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('oauth_providers', sa.Column('provider_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'oauth_providers', type_='unique')
    # ### end Alembic commands ###
